
version: "3"
services:
  gumball:
    image: paulnguyen/gumball
    ports:
      - "9000:3000"
    networks:
      - webnet
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672" 
    networks:
      - webnet
  mongodb:
    image: mongo:3.7
    networks:
      - webnet
networks:
  webnet: