/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pnguyen' at '11/6/16 4:07 PM' with Gradle 3.1
 *
 * @author pnguyen, @date 11/6/16 4:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
