sudo: required
dist: trusty
language: java
jdk: oraclejdk8
env:
  - RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.7/ubuntu/trusty/riak_2.0.7-1_amd64.deb
  - RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.2/2.2.0/ubuntu/trusty/riak_2.2.0-1_amd64.deb
script:
  - jdk_switcher use oraclejdk8
  - sudo ./travis-ci/riak-install -d "$RIAK_DOWNLOAD_URL"
  - sudo ./setup-riak -s
  - sudo riak-admin security disable
  - curl -4vvv localhost:8098/stats
notifications:
  slack:
    secure: G2MNdVq1TLLa2LrRZ9r0Wzp9/fs6P0n2KJ21kATrOgK0MXm2bcYeFnkztc8T8cbBlQf9JVTFKNgmEleKTXGYvGcMPnMJ5J3xlXyfz0AMnU+bn55gaLr7qBGZHfMyr3ZcQN6iFzJdNVxbrmNbfUlQA5rg/6bDdJcYZ3enHjmXWZo=
